name: "🐋Build Docker image"

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Version o tag de la imagen
        required: true
        default: latest
      external_port:
        type: number
        description: Puerto donde el servicio será expuesto a la red
        required: false
        default: 81
      internal_port:
        type: number
        description: Puerto donde corre el servicio dentro del contenedor
        required: false
        default: 8000

env:
  IMAGE_NAME: ghcr.io/sintergicaai/anton

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login on GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: GTWALOM
          password: ${{ secrets.ANTON_TOKEN }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup buildx
        uses: docker/setup-buildx-action@v1.0.0

      - name: Build image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          tags: ${{ env.IMAGE_NAME }}:${{ inputs.tag }},${{ env.IMAGE_NAME }}:latest
          platforms: linux/amd64,linux/arm64
          push: true