name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run pytest
        uses: pavelzw/pytest-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.ANTON_TOKEN }}
        with:
          verbose: true
          emoji: true
          job-summary: true
          custom-arguments: '-q'
          click-to-expand: true
          report-title: 'Test Report'